name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/**/*.{js,ts,svelte,html}"
      - "packages/**/package.json"
      - "buildResources"
      - "package-lock.json"
      - "package.json"
      - "electron-builder.mjs"
      - "scripts/extractLastReleaseChangelog.js"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "packages/**/*.{js,ts,svelte,html}"
      - "packages/**/package.json"
      - "buildResources"
      - "package-lock.json"
      - "package.json"
      - "electron-builder.mjs"
      - "scripts/extractLastReleaseChangelog.js"

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: ./.github/workflows/compile-and-test.yml

  publish-bridge-server:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      id-token: write
    needs:
      - compile-and-test
    uses: ./.github/workflows/publish-bridge-server.yml

  release:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    needs:
      - compile-and-test
      - publish-bridge-server
    uses: ./.github/workflows/release.yml

  deploy-landing-page:
    permissions:
      pages: write
      id-token: write
    needs:
      - release
    uses: ./.github/workflows/deploy-landing-page.yml
